backend:
  name: github
  repo: wakeupgoo/bimbel-edumag # Harus sesuai dengan repo di gambar
  branch: main # Gunakan 'main' sesuai branch utama Anda
  # HAPUS baris site_id, base_url, atau auth_endpoint jika sebelumnya ada
  
publish_mode: editorial_workflow

media_folder: "public/assets/img/uploads"
public_folder: "/assets/img/uploads" 

collections:
  - name: "article"
    label: "Artikel Blog"
    folder: "public/_articles" # Folder penyimpanan artikel
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Kategori", name: "category", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Isi", name: "body", widget: "markdown"}